# Generated by Django 2.0.5 on 2018-05-16 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180516_0809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='username',
            new_name='email',
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
