# Generated by Django 2.0.5 on 2018-05-16 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_acount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturer',
            old_name='username',
            new_name='name',
        ),
    ]
