# Generated by Django 2.0.5 on 2018-05-16 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180516_0848'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
