# Generated by Django 2.0.5 on 2018-05-16 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mssv', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('student_class', models.CharField(max_length=50)),
            ],
        ),
    ]
