# Generated by Django 2.0.5 on 2018-05-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer_class',
            name='classid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lecturer_class',
            name='lecturerId',
            field=models.IntegerField(default=0),
        ),
    ]
