# Generated by Django 2.0.5 on 2018-05-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20180517_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='classId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
