# Generated by Django 2.0.5 on 2018-05-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='point',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='point2',
            field=models.FloatField(null=True),
        ),
    ]
