# Generated by Django 2.0.4 on 2018-05-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20180519_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='logincheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('logged_id', models.IntegerField(default=-1)),
            ],
        ),
    ]
